### ISSUE TITLE
直接使用代码，运行test用例，抛出空指针异常

### ISSUE THREAD

**Issue by HappyFerry** [caryyu/excel2pdf#1]
java.lang.NullPointerException

**Comment by caryyu** [comment]
你的Excel文件有设置成A4版式吗？另外方便把你详细的使用步骤说一下嘛？

**Comment by caryyu** [comment]
@HappyFerry 你的Excel文件有设置成A4版式吗？另外方便把你详细的使用步骤说一下嘛？

**Comment by ONopHX** [comment]
Exception in thread "main" java.lang.NullPointerException
	at com.springboot.demo.u.PdfTableExcel.toParseContent(PdfTableExcel.java:69)
	at com.springboot.demo.u.PdfTableExcel.getTable(PdfTableExcel.java:54)
	at com.springboot.demo.u.Excel2Pdf.toCreatePdfTable(Excel2Pdf.java:126)
	at com.springboot.demo.u.Excel2Pdf.convert(Excel2Pdf.java:108)
	at com.springboot.demo.util.PDFTest.main(PDFTest.java:25)


同样的问题，

**Comment by caryyu** [comment]
能否提供样板 xls 文件供我调试,谢谢!

**Comment by caryyu** [comment]
使用最新代码再次尝试。
