### ISSUE TITLE
excel文件内有图片及图形的情况下报错

### ISSUE THREAD

**Issue by yang-mtr001** [caryyu/excel2pdf#8]
Exception in thread "main" java.io.IOException: The byte array is not a recognized imageformat.
at com.itextpdf.text.Image.getInstance(Image.java:474)
at com.itextpdf.text.Image.getInstance(Image.java:375)
at itextpdf.PdfTableExcel.addImageByPOICell(PdfTableExcel.java:208)
at itextpdf.PdfTableExcel.toParseContent(PdfTableExcel.java:115)
at itextpdf.PdfTableExcel.getTable(PdfTableExcel.java:54)
at itextpdf.Excel2Pdf.toCreatePdfTable(Excel2Pdf.java:126)
at itextpdf.Excel2Pdf.convert(Excel2Pdf.java:108)
at itextpdf.TestMain.main(TestMain.java:28)

**Comment by caryyu** [comment]
能否把相应的 xls 文件上传上来供我这边调试,谢谢!

**Comment by PingWei1314** [comment]
请问这个问题解决了吗
我现在也遇到了，用poi生成excel里有图片，文字可以转换过去，图片却不行
